### ISSUE TITLE
Getting rid of 'allow full screen' box.

### ISSUE THREAD

**Issue by eschnou** [MozVR/panorama-viewer#2]
When using this app for the first time, the 'allow full-screen' dialog appears in the oculus view (barely visible at the top of the headset view).

I did not figure out the key to press to allow and can't find a way to solve this.

Only solution to get rid of the box was to edit my browser config (about:config) and set the following parameter to false:  full-screen-api.approval-required

**Comment by caseyyee** [comment]
We have filed bugs for this issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1121626

Until that is fixed, the workaround that we have in place now isL
1. requestFullscreen without vrDisplay option (so that the content renders to the users main display)
2. Prompt the user to allow the permission.
3. request fullscreen with the vrDisplay option:  requestFullscreen({vrDisplay: vrDisplay}) 

You can see this is how we have implemented it on mozvr.com.   It's ugly, but its the best that can be done right now.

**Comment by caseyyee** [comment]
This is a issue with how Firefox handles permission prompts.   Closing this issue since it is being tracked in bugzilla.
